name: ğŸ® Build & Export Game
on: [push, pull_request, merge_group]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true
  
jobs:
  # First stage: Only static checks, fast and prevent expensive builds from running.
  static-checks:
    if: ${{ !vars.DISABLE_GODOT_CI || github.run_attempt > 1 }}
    name: ğŸ“Š Static checks
    uses: ./.github/workflows/static_checks.yml
    secrets: inherit

  # Second stage: Run all the builds
  linux-build:
    name: ğŸ§ Linux
    needs: static-checks
    uses: ./.github/workflows/linux_builds.yml
    secrets: inherit
    
  macos-build:
    name: ğŸ MacOS
    needs: static-checks
    uses: ./.github/workflows/macos_builds.yml
    secrets: inherit

  windows-build:
    name: ğŸªŸ Windows
    needs: static-checks
    uses: ./.github/workflows/windows_builds.yml
    secrets: inherit
    
  web-build:
    name: ğŸŒ Web
    needs: static-checks
    uses: ./.github/workflows/web_builds.yml
    secrets: inherit
    
  android-build:
    name: ğŸ¤– Android
    needs: static-checks
    uses: ./.github/workflows/android_builds.yml
    secrets: inherit

  ios-build:
    name: ğŸ iOS Builds
    needs: static-checks
    uses: ./.github/workflows/ios_builds.yml
    secrets: inherit
