name: üêß Linux
on:
  workflow_call:

jobs:
  build-and-export:
    #timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            #{ platform: linux, arch: arm32, os: ubuntu-22.04-arm, upload-artifact: false },
            #{ platform: linux, arch: arm64, os: ubuntu-22.04-arm, upload-artifact: false },
            #{ platform: linux, arch: x86_32, os: ubuntu-22.04, upload-artifact: false },
            { platform: linux, arch: x86_64, os: ubuntu-22.04, upload-artifact: false },
          ]
        #target-type: [template_debug, template_release, profile, production]
        #float-precision: [single, double]
        target-type: [template_debug, production]
        float-precision: [single]
        
    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Lint
      #- name: Setup clang-format
      #  shell: bash
      #  run: |
      #    python -m pip install clang-format
      #- name: Run clang-format
      #  shell: bash
      #  run: |
      #    clang-format src/** --dry-run --Werror

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}

      - name: Setup Dependencies
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get install mesa-vulkan-drivers
          sudo apt-get install libwayland-bin
          echo "Disk usage before:" && df -h
          sudo rm -rf /usr/local/lib/android
          echo "Disk usage after:" && df -h
          
      # Add linux x86_32 toolchain
      - name: Install 32 Bit Support
        if: ${{ matrix.target.arch == 'x86_32' }}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib
          
      - name: Setup Workflow Variables
        run: |
          python tools/scripts/write_to_github_actions_environment.py
    
      # Restore .scons_cache
      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
      
      # Build Engine + GDExtension (with caches)
      - name: Build Project
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/build.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      - name: Create Custom Export Template
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/create_custom_export_template.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      # Save scons cache
      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
        continue-on-error: true
      
      - name: Export Project
        if: ${{ matrix.target.arch != 'arm32' }}
        shell: sh
        run: |
          python tools/scripts/export.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True

      - name: Unit Tests
        if: ${{ matrix.target-type == 'template_debug' }}
        run: |
          python tools/scripts/run_unit_tests.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
        continue-on-error: true

      # Upload the build
      - name: Upload Artifact
        if: ${{ matrix.target.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: game_${{ matrix.target.platform }}_${{ matrix.target-type }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ env.BUILD_TIME }}_${{ github.ref_name }}_${{ env.SHA_SHORT }}
          path: |
            ${{ github.workspace }}/bin/${{ matrix.target.platform }}/**
          retention-days: 2