name: üåê Web
on:
  workflow_call:

jobs:
  build-and-export:
    #timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { platform: web, arch: wasm32, os: windows-latest }
          ]
        target-type: [template_debug, template_release, profile, production]
        float-precision: [single, double]

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: latest
          windows-compiler: msvc

      - name: emsdk
        run: |
          thirdparty/emsdk/emsdk.bat install latest --build=Release
          thirdparty/emsdk/emsdk.bat activate latest
    
      - name: Setup Workflow Variables
        run: |
          python tools/scripts/write_to_github_actions_environment.py
    
      # Restore .scons_cache
      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
      
      # Build Engine + GDExtension (with caches)
      - name: Build Project
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/build.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      - name: Create Custom Export Template
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/create_custom_export_template.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      # Save scons cache
      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
        continue-on-error: true
        
      - name: Export Project
        shell: sh
        run: |
          python tools/scripts/export.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True

      - name: Unit Tests
        run: |
          python tools/scripts/run_unit_tests.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True

      # Upload the build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game_${{ matrix.target.platform }}_${{ matrix.target-type }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ env.BUILD_TIME }}_${{ github.ref_name }}_${{ env.SHA_SHORT }}
          path: |
            ${{ github.workspace }}/bin/${{ matrix.target.platform }}/**
