name: ðŸªŸ Windows
on:
  workflow_call:

# Global Settings
env:
  SCONS_CACHE_MSVC_CONFIG: true
  
jobs:
  build-and-export:
    # Comment back in when confident with regular commits (within 7 days as that's how long github actions cache last)
    #timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            #{ platform: windows, arch: arm64, os: windows-11-arm },
            #{ platform: windows, arch: x86_32, os: windows-latest },
            { platform: windows, arch: x86_64, os: windows-latest },
          ]
        #target-type: [template_debug, template_release, profile, production]
        #float-precision: [single, double]
        target-type: [template_debug, production]
        float-precision: [single]

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          windows-compiler: msvc

      - name: Setup Workflow Variables
        run: |
          python tools/scripts/write_to_github_actions_environment.py
    
      # Restore .scons_cache
      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
      
      # Build Engine + GDExtension (with caches)
      - name: Build Project
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/build.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      - name: Create Custom Export Template
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/create_custom_export_template.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      # Save scons cache
      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
        continue-on-error: true
        
      - name: Export Project
        shell: sh
        run: |
          python tools/scripts/export.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      # Clean up compilation files
      - name: Delete compilation files
        shell: pwsh
        run: |
          Remove-Item bin/${{ matrix.target.platform }}/* -Include *.exp,*.lib,*.pdb -Force

      - name: Unit Tests
        run: |
          python tools/scripts/run_unit_tests.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True

      # Upload the build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game_${{ matrix.target.platform }}_${{ matrix.target-type }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ env.BUILD_TIME }}_${{ github.ref_name }}_${{ env.SHA_SHORT }}
          path: |
            ${{ github.workspace }}/bin/${{ matrix.target.platform }}/**
